### ISSUE TITLE
Build s2i-custom-notebook image with different base images.

### ISSUE THREAD

**Issue by harshad16** [AICoE/s2i-custom-notebook#18]
**Is your feature request related to a problem? Please describe.**
s2i-custom-notebook image is built with s2i-minimal-notebook which supports CPU architecture, enable s2i-custom-notebook to be built with GPU based base image for enabling it to support GPU architecture.

**Describe the solution you'd like**
Update the pipeline to build multiple images of s2i-custom-notebooks with different base images (CPU&GPU).

**Describe alternatives you've considered**
openshift buildconfigs with different base images initiated.

**Additional context**
Some of the projects requires GPU architecture, the GPU image is required for those project to function without environmental errors.

**Comment by 4n4nd** [comment]
We could create a new base image called `s2i-custom-gpu-notebook` but how would the build pipeline work?

**Comment by harshad16** [comment]
> We could create a new base image called `s2i-custom-gpu-notebook` but how would the build pipeline work?

yeah, that sounds good.
we have a custom pipeline to build multiple images for a project through aicoe-ci, we can test with it.
