### ISSUE TITLE
Convert Gdoc guide to have it available here as an user guide

### ISSUE THREAD

**Issue by tumido** [AICoE/s2i-custom-notebook#25]
Please convert the [Package Jupyter Notebook google doc](https://docs.google.com/document/d/1l54w8VnV_rth-30g2AVbtN9sfDKhu4jg9AR9xvred0A/edit) into a Markdown page on Github, either here or in the https://github.com/aicoe-aiops/data-science-workflows to cover the onboarding + usage. Most importantly document a link to the appropriate [Tekton dashboard](http://tekton-dashboard-tekton-pipelines.apps.thoth12.lab.upshift.rdu2.redhat.com/#/namespaces/jupyternb/pipelineruns?labelSelector=tekton.dev%2Fpipeline%3Djupyternb-pipeline), where builds can be checked, [the OCP registry](https://registry-console.upshift.redhat.com/registry#/images/aicoe-notebooks) link, where the images are stored, etc. So the users have some visibility into what is really going on (if the pipeline was triggered or not, what's the image tags available in the registry etc.)... 

@durandom  would you rather see the docs here or in the https://github.com/aicoe-aiops/data-science-workflows

**Comment by harshad16** [comment]
@tumido , Most of the required information about the s2i-custom-notebook is being added to the Markdown, and about the pipeline is already been added to the [pipeline repository](https://github.com/harshad16/jupyternb-build-pipeline). however, surely we can added the relevant on-boarding information on the aicoe-ci repository, so users can swiftly onboard.
thanks for pointing this out.

**Comment by durandom** [comment]
I've already asked for that conversion on https://github.com/AICoE/s2i-custom-notebook/issues/8 

@4n4nd could please move the documentation into this repo here soon?
