### ISSUE TITLE
Custom s2i scripts are not executed 

### ISSUE THREAD

**Issue by tumido** [AICoE/s2i-custom-notebook#29]
**Describe the bug**
`s2i` scripts in the target repository are not executed. The repository is built as an S2I repo, but the `.s2i` folder is ignored. 

**To Reproduce**
1. See https://github.com/aicoe-aiops/openshift-sme-mailing-list-analysis
2. Release new version
3. See the build result http://tekton-dashboard-tekton-pipelines.apps.thoth12.lab.upshift.rdu2.redhat.com/#/namespaces/jupyternb/pipelineruns/jupyternb-pipeline-build-xvq4l (see logs of the `build` step)
4. See that the [custom s2i assemble script](https://github.com/aicoe-aiops/openshift-sme-mailing-list-analysis/blob/master/.s2i/bin/assemble) was not executed (`---> Installing spacy models ...` missing from logs)

**Expected behavior**
`.s2i` scripts and env variables would be set and respected

Blocker for: https://github.com/aicoe-aiops/openshift-sme-mailing-list-analysis/pull/3 (attempts for a build unification - to use the image built by `s2i-custom-notebook` instead of a custom s2i image)

**Comment by tumido** [comment]
cc @harshad16 @4n4nd 

I've tried to workaround this (by inlining files into Pipfile, since our repo only uses assemble script to install `spacy` packages) but I hit https://github.com/thoth-station/jupyternb-build-pipeline/pull/1 anyways.

**Comment by harshad16** [comment]
@tumido  thanks for the fix with thoth-station/jupyternb-build-pipeline#1, it was earlier missed. 
about the `.s2i`  files present in the repository, we had a discussion about this early and point was raised that their won't be `.s2i` files in the notebook repositories. If there would be such then, we can work on something to get it in.
@4n4nd sync

**Comment by 4n4nd** [comment]
Yeah we had decided to not execute any scripts from `.s2i` early on to keep things simple, but if we need it rn we could execute `.s2i/assemble` in the top of `s2i-custom-notebook` assemble script

**Comment by tumido** [comment]
Yeah, I get that notebook images by itself may not need any s2i scripts at all. I understand that I'm kinda abusing your pipeline and images to execute them in automation. They were not supposed to support that. On the other hand I rather have a single image for a s2i repo than multiple images that differ in s2i support only. That's why I'm trying so hard to use your image in https://github.com/aicoe-aiops/openshift-sme-mailing-list-analysis/pull/3 . :smile: 

On the other hand, so far I've successfully managed to workaround the `assemble` script requirement I had. And the workaround made me do things properly and in a way that is even better that the assemble script originally worked. :shrug: 

Right now I don't have any strict requirement for inclusion of these scripts. I would like to see them in there, just so we can claim that we truly support the s2i protocol. Otherwise I would prefer if we can mention that we don't support any `.s2i/*` file (not just scripts, but `environment` as well) in the README to avoid the confusion I had.

I think we can revisit this issue if the requirement for those scripts surfaces any time later again.

**Comment by 4n4nd** [comment]
Yeah it's not like we are against it, it's just that we never needed it so we never implemented it. If someone needs it, we can do that.
>  if we can mention that we don't support any .s2i/* file (not just scripts, but environment as well) in the README to avoid the confusion I had.

Yeah we should do that

> I think we can revisit this issue if the requirement for those scripts surfaces any time later again.

:+1:

**Comment by harshad16** [comment]
The pipeline failed in the build execution of **aicoe-aiops/openshift-sme-mailing-list-analysis** project image as `micropipenv` as of now doesn't support [installation from file ](https://github.com/aicoe-aiops/openshift-sme-mailing-list-analysis/blob/aece0034fab78abcdc8620664adb8e60180b1b98/Pipfile#L13).
we have opened an [issue](https://github.com/thoth-station/micropipenv/issues/99) in `micropipenv` to accommodate this feature requirement.

Here are some of the possible visible options, 
- we work on getting the feature into `micropipenv` to install from file.
or
- we can install `pipenv` in `s2i-thoth-ubi8-py36` base image and have a flag, which enables the switch between `pipenv` and `micropipenv`(default).

**Comment by tumido** [comment]
Fix is on the way! :gift: https://github.com/thoth-station/micropipenv/pull/100

**Comment by harshad16** [comment]
Thanks @tumido for the PR https://github.com/thoth-station/micropipenv/pull/100.
micropipenv newest version is updated with v0.5.0, which includes the fix.
all the base images are updated s2i-thoth-ubi8-py36, s2i-minimal-notebook, s2i-custom-notebook with updated micropipenv.
please trigger the tag release again, let's check on the pipeline.

**Comment by harshad16** [comment]
The image was created by the pipeline and pushed.
here: docker-registry.upshift.redhat.com/aicoe-notebooks/openshift-sme-mailing-list-analysis:v0.03.4_pre3

**Comment by tumido** [comment]
@harshad16 :medal_sports: Thank you! :100:
