### ISSUE TITLE
autogenerate README.md in notebooks folder

### ISSUE THREAD

**Issue by durandom** [AICoE/s2i-custom-notebook#3]
just a thought. The point is to start collaboration. Can we autogenerate a README to copied into the notebooks folder that contains some meta information, e.g. the source repo, the authors, the latest commit date etc

**Comment by harshad16** [comment]
@durandom we definitely can include a README. 
The user(in this case is the developer) would have to include that README in their repo, as we are packaging the notebook dir, along with it we can package the README.

@4n4nd  WDYT? Thoughts?

**Comment by 4n4nd** [comment]
I like the idea, I am just not sure where we will be getting the repo information from.

**Comment by harshad16** [comment]
Autogenerated information can be the information present in the webhook details.
Pipeline can be added with a tasks to include a README with information present in webhook.
like commit sha, repo_name. 
we can start with something small. as gitlab webhook contains less info than github webhook.

**Comment by 4n4nd** [comment]
This was implemented in https://github.com/AICoE/s2i-custom-notebook/pull/5
