### ISSUE TITLE
Collaborating on jupyter notebook project through images.

### ISSUE THREAD

**Issue by harshad16** [AICoE/s2i-custom-notebook#7]
As the current pipeline only create an image with all environment set up along with the notebooks present, it is simply a demo/workshop notebook image. Through which a user can view and run experiment on the jupyter notebook present in the image. 
However a user can't collaborate from this image, as this doesn't contain git information. This arise some questions:
- Does this image be even used for collaboration or these are simply for the sake of a demo/workshop?
- If a user decides to contribute something then they would git clone the repo, which would get the upstream repo, which user can contribute to push and later raise a PR. or Else we would have to create a separate image which would contain all the information and anyone using that can keep updating upstream.

Is the current pipeline reaching the goal or should there be a feature which on push to the master of upstream, build an image with all content and which is latter readily available in jupyterhub?
What are your thoughts on this @goern @durandom  @4n4nd

**Comment by goern** [comment]
I would like to see the collaborator story of ODH. 

https://github.com/orgs/opendatahub-io/projects/1#card-38767078

**Comment by harshad16** [comment]
closing this issue, as we have newer stories with meteor project.
thanks for the brains.
