### ISSUE TITLE
Elyra  image update

### ISSUE THREAD

**Issue by Shreyanand** [AICoE/s2i-custom-notebook#77]
This image leverages the Elyra framework and is used as a base image in downstream projects like [aicoe-osc-demo](https://github.com/os-climate/aicoe-osc-demo). The latest Elyra version includes a lot of features that are missing in the current version. If this image can be updated with the latest version and better yet, always be up to date together with the elyra lab image, the os-climate projects would benefit from the latest additions.

**Comment by harshad16** [comment]
Thanks for the issue.
can you elaborate a little more on what latest version is to be targeted?

with merged of linked pr: `elyra version v3.10.1`
would be included in the `s2i-custom-elyra-notebook` image. 

are we looking for the latest https://github.com/elyra-ai/elyra/releases/tag/v3.13.0 ?

**Comment by Shreyanand** [comment]
One of the updates I'm looking for came in v3.8.0 so v3.10.1 should be ok. I'm gonna try it and if I run into errors I'll reach out. Thanks for updating!
