### ISSUE TITLE
document how to get a new content notebook into Data Hub

### ISSUE THREAD

**Issue by goern** [AICoE/s2i-custom-notebook#8]
**Is your feature request related to a problem? Please describe.**
after we have worked on the notebooks and created a container image using s2i-custom-notebook, how do we get into internal Data Hub or ODH?

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
TBD

**Additional context**
n/a

**Comment by goern** [comment]
@AICoE/aiops @vpavlin

**Comment by goern** [comment]
@harshad16 @pacospace

**Comment by harshad16** [comment]
I will include that in the documentation.
Procedure to include the new content notebook into Data Hub, is to tag the image of the content image present in the [internal registry](https://registry-console.upshift.redhat.com/registry#/images/aicoe-notebooks) to datahub registry. Following command can be used: 
```
oc tag --source=docker 'docker-registry.upshift.redhat.com/aicoe-notebooks/project-name>:<latest or vX.Y.Z>' 's2i-<project-name>-notebook:latest' -n <jupyterhub-namespace>
``` 
we can have images delivery to datahub via argo, or if need tekton can delivery as well, would need a service account for that.

**Comment by harshad16** [comment]
Pointed by @4n4nd  the imagestream also needs a label for jupyterhub to pick the imagestream.
@4n4nd would be updating the documentation.

**Comment by durandom** [comment]
@4n4nd can you open a PR with the google doc harshad and you created? Don't worry about internal hostnames and such

**Comment by durandom** [comment]
The current documentation is in https://docs.google.com/document/d/1l54w8VnV_rth-30g2AVbtN9sfDKhu4jg9AR9xvred0A/edit#heading=h.241uuvxbut12

**Comment by harshad16** [comment]
This issue was completed 
all the documentation is available on the readme
https://github.com/AICoE/s2i-custom-notebook#how-to-add-the-image-to-open-data-hubjupyterhub
thanks to @4n4nd
